### ISSUE TITLE
HTTP 403 on Youtube videos converted to HTML 5 video

### ISSUE THREAD

**Issue by browndav** [hoyois/clicktoplugin#116]
Hi,

Thanks for the awesome Safari extension.

I just noticed this morning that a relatively large number of Youtube videos are failing with an HTTP 403 after they're converted to HTML5 video. These videos work in Flash mode. I'm currently using Safari 7.1.4 (9537.85.13.7), with all other extensions disabled.

Here's a video that's failing: https://www.youtube.com/watch?v=8wlGgzpDsPM
Here's one that's working: https://www.youtube.com/watch?v=Xj6oI-QkJYg

Here's a quick screenshot of what the failure looks like:

![http-403-20150327](https://cloud.githubusercontent.com/assets/763977/6868781/976f1d58-d44b-11e4-8ca2-2c99a2255f87.jpg)

It's entirely possible that this is a temporary issue on Google's side, but I figured I'd file an issue just in case something changed/broke permanently.

Thanks!

**Comment by hoyois** [comment]
Thanks for the report. It just started happening for me as well. Could you try replacing the built-in killer with the following?

 https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTube.js

**Comment by JohnBlackburne** [comment]
Another example, 403 error also:
https://www.youtube.com/watch?v=SQXqkiKXiHc
I'll give the new killer a try.

**Comment by hoyois** [comment]
OK, thanks for checking. This might only be a temporary fix but at least I understand the source of the problem now.

**Comment by browndav** [comment]
The fix worked for me too. A quick patch and xar/openssl re-sign and it's working again. Thanks!

**Comment by hjstephens09** [comment]
I'm having this issue as well.

**Comment by hoyois** [comment]
This is fixed for now.

**Comment by hoyois** [comment]
Broken again, will fix.

**Comment by hoyois** [comment]
Can use https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTubeS.js in the meantime.

**Comment by browndav** [comment]
I'm still getting a 403 from https://www.youtube.com/watch?v=8wlGgzpDsPM using the updated YouTubeS.js; here's the address it's trying to pull:

```
https://r7---sn-o097znle.googlevideo.com/videoplayback?ip=$MY_IP_ADDRESS&mm=31&requiressl=yes&upn=HCGtYV4GUYM&ratebypass=yes&itag=18&key=yt5&mime=video%2Fmp4&fexp=900720%2C907263%2C912151%2C934954%2C936928%2C937247%2C9405637%2C9405973%2C9406633%2C9406911%2C9408101%2C9408224%2C948124%2C948703%2C951511%2C951703%2C952612%2C953919%2C957201%2C961404%2C961406&mt=1427909753&sver=3&id=o-ADyz_sPvtzbexsjuA9O4qMydBo0N0X2trFi_Wt1QY2UE&dur=265.102&expire=1427931420&pl=20&source=youtube&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&ipbits=0&ms=au&signature=4A2ABB72E5A79370C26F595BD6221D1370FDDC3583.3BDACF1120558AC9B6A285F1DBD240B699983102&title=Polyethylene%20%5Bparts%201%20%26%202%5D%20-%20Radiohead%20%5B360p%5D
```

**Comment by hoyois** [comment]
Did you close the preference window after changing the URL?

**Comment by browndav** [comment]
Yeah, I uninstalled the extension, reset Safari, overwrote Youtube.js with YoutubeS.js, rebuilt a new safariextz, and installed it. I'll try one more time over lunch just to make sure I didn't hose something up.

**Comment by hoyois** [comment]
Hold on, there's no need to rebuild the extension every time. You can just put the URL in the list of conversion scripts in the preferences.

**Comment by browndav** [comment]
I'll try it with the URL. Honestly, I only rebuilt it because I wanted to figure out how to do the signing manually with xar/openssl. Masochism, I guess.

**Comment by browndav** [comment]
Unfortunately still no-go dropping https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTubeS.js in to the killer list and closing the preferences tab. I tried both replacing the existing `killers/Youtube.js` line with it, and (for no apparent reason) adding it in addition to the default `killers/Youtube.js`.

Not sure if this is helpful or even related, but I also seem to get the Flash placeholder the first time I load https://www.youtube.com/watch?v=8wlGgzpDsPM after changing the killers list. A reload fixes it. Not a big deal, but I figured it was worth mentioning.

**Comment by hoyois** [comment]
@browndav Might be it's related, yes. The latter is not supposed to happen either. Since you've compiled the extension, can you check the value of killers.YouTube.decoder in the extension's global page?

**Comment by electric-monk** [comment]
I'm also experiencing this - it looks like the videos that don't work are almost exclusively music videos, so I assume it's some flag the content owners are setting.

**Comment by hoyois** [comment]
@electric-monk The source of the problem is well understood: it's signature encryption. But I need to figure put why YouTubeS.js is not working for some. Does it work for you?

**Comment by JohnBlackburne** [comment]
YouTubeS.js works for me on a video I had problems on earlier, HGawnVcpzB4 and the above 8wlGgzpDsPM, both of which are broken with the built in killer.

**Comment by electric-monk** [comment]
Ooh yeah, it's working now, thanks!

**Comment by gitguys** [comment]
Not working with any Vevo videos whatsoever at this point.

https://www.youtube.com/results?search_query=vevo

**Comment by hoyois** [comment]
Hopefully this is fixed for everyone in CTP 3.1.2. Please reopen if not.

**Comment by browndav** [comment]
Working for me now with 3.1.2. Thanks again!
